I want to write a test to establish that an Exception is not raised in a given circumstance. It\'s straightforward to test if an Exception is raised ...... but how can you do the opposite. Something like this i what I\'m after ...Just call the function.  If it raises an exception, the unit test framework will flag this as an error.  You might like to add a comment, e.g.:Hi - I want to write a test to establish that an Exception is not raised in a given circumstance.That\'s the default assumption -- exceptions are not raised.If you say nothing else, that\'s assumed in every single test.You don\'t have to actually write an any assertion for that. I am the original poster and I accepted the above answer by DGH without having first used it in the code. Once I did use I realised that it needed a little tweaking to actually do what I needed it to do (to be fair to DGH he/she did say "or something similar" !). I thought it was worth posting the tweak here for the benefit of others:What I was attempting to do here was to ensure that if an attempt was made to instantiate an Application object with a second argument of spaces the pySourceAidExceptions.PathIsNotAValidOne would be raised. I believe that using the above code (based heavily on DGH\'s answer) will do that.If you pass an Exception class to assertRaises(), a context manager is provided. This can improve the readability of your tests:This allows you to test error cases in your code. In this case, you are testing the PathIsNotAValidOne is raised when you pass invalid parameters to the Application constructor.