I am trying to use networkx with Python. When I run this program it get this error. Is there anything missing?I get a different error now:I get a different error now:The main problem is that (on your system) matplotlib chooses an x-using backend by default. I just had the same problem on one of my servers.  The solution for me was to add the following code in a place that gets read before any other pylab/matplotlib/pyplot import:The alternative is to set it in your .matplotlibrcJust as a complement of Reinout\'s answer.The permanent way to solve this kind of problem is to edit .matplotlibrc file. Find it viaThen modify the backend in that file to backend : Agg. That is it.I will just repeat what @Ivo Bosticky said which can be overlooked. Put these lines at the VERY start of the py file.Or one would get error This will resolve all Display issueThe clean answer is to take a little bit of time correctly prepare your execution environment.The first technique you have to prepare your execution environment is to use a matplotlibrc file, as wisely recommended by Chris Q., settingin that file. You can even control \xe2\x80\x94 with no code changes \xe2\x80\x94 how and where matplotlib looks for and finds the matplotlibrc file.The second technique you have to prepare your execution environment is to use the MPLBACKEND environment variable (and inform your users to make use of it):This is handy because you don\'t even have to provide another file on disk to make this work. I have employed this approach with, for example, testing in continuous integration, and running on remote machines that do not have displays.Hard-coding your matplotlib backend to "Agg" in your Python code is like bashing a square peg into a round hole with a big hammer, when, instead, you could have just told matplotlib it needs to be a square hole.When signing into the server to execute the code\nuse this instead:the -X will get rid of the no display name and no $DISPLAY environment variable\nerror:)I got the error while using matplotlib through Spark. matplotlib.use(\'Agg\') doesn\'t work for me. In the end, the following code works for me. More hereI found this snippet to work well when switching between X and no-X environments.What system are you on? It looks like you have a system with X11, but the DISPLAY environment variable was not properly set. Try executing the following command and then rerunning your program:One other thing to check is whether your current user is authorised to connect to the X display. In my case, root was not allowed to do that and matplotlib was complaining with the same error.source: http://www.debian-administration.org/articles/494For Google Cloud Machine Learning Engine:And then to print to file:and to create the PDF: