I have four different files named: main, vector, entity, and physics. I will not post all the code, mostly just the imports, because I think that\'s where the error is. But if you want, I can post more.Main:Entity:Vector:Physics:I then run from main.py and I get the following error:I am very new to python, but have worked with C++ for a long time. I am guessing that the cause is from importing entity twice, once in main, and later in physics, but I don\'t know a workaround. Anyone help?You have circular dependent imports. physics.py is imported from entity before class Ent is defined and physics tries to import entity that is already initializing. Remove the dependency to physics from entity module.While you should definitely avoid circular dependencies, you can defer imports in python.for example:this ( at least in some instances ) will circumvent the error.This is a circular dependency. It can be solved without any structural modifications to the code. The problem occurs because in vector you demand that entity be made available for use immediately, and vice versa. The reason for this problem is that you asking to access the contents of the module before it is ready -- by using from x import y. This is essentially the same asPython is able to detect circular dependencies and prevent the infinite loop of imports. Essentially all that happens is that an empty placeholder is created for the module (ie. it has no content). Once the circularly dependent modules are compiled it updates the imported module. This is works something like this.For python to be able to work with circular dependencies you must use import x style only.Since you are no longer referring to the contents of the module at the top level, python can compile the module without actually having to access the contents of the circular dependency. By top level I mean lines that will be executed during compilation as opposed to the contents of functions (eg. y = x.y). Static or class variables accessing the module contents will also cause problems.I just got this error too, for a different reason...The main script had Windows line endings. my_sub_module had UNIX line endings. Changing them to be the same fixed the problem. They also need to have the same character encoding.Python is case sensitive, so entity != Entity. I suggest you change the casing of entity in your imports to be Entity. This will fix your problem. Your Main should be like this\nMain: