This question already has an answer here:I have a try...except block in my code and When an exception is throw. I really just want to continue with the code because in that case, everything is still able to run just fine. The problem is if you leave the except: block empty or with a #do nothing, it gives you a syntax error. I can\'t use continue because its not in a loop. Is there a keyword i can use that tells the code to just keep going?The standard "nop" in Python is the pass statement:Because of the last thrown exception being remembered in Python, some of the objects involved in the exception-throwing statement are being kept live indefinitely (actually, until the next exception). In case this is important for you and (typically) you don\'t need to remember the last thrown exception, you might want to do the following instead of pass:This clears the last thrown exception.There\'s a new way to do this coming in Python 3.4:Here\'s the commit that added it: http://hg.python.org/cpython/rev/406b47c64480And here\'s the author, Raymond Hettinger, talking about this and all sorts of other Python hotness (relevant bit at 43:30): http://www.youtube.com/watch?v=OSGv2VnC0goIf you wanted to emulate the bare except keyword and also ignore things like KeyboardInterrupt\xe2\x80\x94though you usually don\'t\xe2\x80\x94you could use with suppress(BaseException).Edit: Looks like ignored was renamed to suppress before the 3.4 release.Try this: